extends SceneTree

func _initialize() -> void:
 call_deferred("run")

func run() -> void:
 root.set_meta("offline_session", true)
 var game: Node = load("res://main.tscn").instantiate()
 root.add_child(game)
 game.online.disabled = true
 game.set_process(false)
 game.start_run("training")
 assert(game.run_active and game.test_run and game.prevent_player_death)
 game.update_game(1.0)
 assert(game.enemies.is_empty(), "Treino deve começar sem geração automática")
 game.training.act("piranha")
 assert(game.enemies.size() == 100 and not game.enemies[0].tank)
 game.training.act("pintado")
 assert(game.enemies.size() == 200 and game.enemies.back().tank)
 game.training.act("boss")
 assert(game.enemies.back().boss)
 game.training.act("fish_clear")
 assert(game.enemies.size() == 1 and game.enemies[0].boss)
 game.training.act("clear")
 assert(game.enemies.is_empty() and not game.boss_spawned)
 game.training.act("time")
 assert(game.elapsed == 61.0)
 var tab := InputEventKey.new()
 tab.keycode = KEY_TAB
 tab.pressed = true
 game.training._input(tab)
 assert(game.state == "playing", "Tab deve alternar a guia sem pausar")
 assert(game.training.editor.visible and not game.training.controls.visible)
 assert(game.training.tab_buttons[1].button_pressed and not game.training.tab_buttons[0].button_pressed)
 assert(not game.training.values.damage.editable)
 game.training.set_stat(75.0, "damage")
 assert(game.damage == 20.0, "Atributos não podem ser editados durante o jogo")
 game.update_game(0.25)
 assert(game.elapsed == 61.25, "Jogo deve continuar com a guia Atributos aberta")
 game.training.tab_buttons[0].pressed.emit()
 assert(game.state == "playing" and game.training.controls.visible and not game.training.editor.visible)
 assert(game.training.tab_buttons[0].button_pressed and not game.training.tab_buttons[1].button_pressed)
 game.training._input(tab)
 game.show_pause()
 assert(game.state == "paused" and game.training.editor.visible and game.training.tabs.visible)
 assert(game.training.values.damage is SpinBox, "Atributo deve permitir digitar um valor manual")
 game.training.values.damage.get_line_edit().text = "75"
 game.training.values.damage.apply()
 assert(game.damage == 75.0, "Valor digitado deve atualizar o personagem")
 game.training.values.damage.value = 20.0
 game.training.values.damage.get_parent().get_child(3).pressed.emit()
 game.training.change_stat("rate", 1)
 game.training.change_stat("level", 1)
 assert(game.damage == 25.0 and game.attack_delay < 0.65 and game.level == 2)
 game.training._input(tab)
 assert(game.state == "paused" and game.training.selected_tab == 0 and not game.training.editor.visible)
 game.training.tab_buttons[1].pressed.emit()
 assert(game.training.editor.visible and game.training.tab_buttons[1].button_pressed)
 game.training.values.damage.value = 30.0
 assert(game.damage == 30.0)
 var field: LineEdit = game.training.values.damage.get_line_edit()
 field.grab_focus()
 field.select_all()
 assert(field.has_focus())
 var escape := InputEventKey.new()
 escape.keycode = KEY_ESCAPE
 escape.pressed = true
 game.training._input(escape)
 assert(game.state == "playing")
 assert(not field.has_focus() and not field.has_selection(), "Retomar deve remover foco e seleção")
 assert(field.focus_mode == Control.FOCUS_NONE)
 assert(game.training.tab_buttons[0].mouse_filter == Control.MOUSE_FILTER_IGNORE)
 assert(game.training.automatic.mouse_filter == Control.MOUSE_FILTER_IGNORE)
 game.training._process(0.0)
 assert(field.focus_mode == Control.FOCUS_NONE)
 game.update_cursor_visibility()
 if DisplayServer.get_name() != "headless": assert(Input.mouse_mode == Input.MOUSE_MODE_HIDDEN)
 assert(game.training.frame.position.x == 16 and game.training.frame.scale.x == 0.5)
 assert(game.training.frame.visible and game.training.tabs.visible)
 assert(game.training.tabs.get_parent() == game.training.controls.get_parent())
 game.show_pause()
 game.update_cursor_visibility()
 assert(Input.mouse_mode == Input.MOUSE_MODE_VISIBLE)
 assert(field.focus_mode != Control.FOCUS_NONE)
 assert(game.training.tab_buttons[0].mouse_filter != Control.MOUSE_FILTER_IGNORE)
 assert(game.training.automatic.mouse_filter != Control.MOUSE_FILTER_IGNORE)
 assert(game.training.tabs.visible and game.training.editor.visible)
 assert(game.training.frame.visible)
 game.resume()
 var history_size: int = game.run_history.size()
 game.record_run("menu")
 assert(game.run_history.size() == history_size, "Treino não deve registrar resultados")
 game.restart_run()
 assert(game.run_mode == "training" and game.damage == 20.0 and game.level == 1)
 game.training.act("level")
 assert(game.state == "upgrade" and game.level == 2)
 game.choose_upgrade("damage")
 assert(game.state == "playing" and game.damage == 24.0)
 game.start_run("bosses")
 assert(not game.test_run and not game.prevent_player_death)
 game.run_recorded = true
 game.show_menu()
 game.update_cursor_visibility()
 assert(Input.mouse_mode == Input.MOUSE_MODE_VISIBLE)
 game.free()
 print("TRAINING ROOM PASS: exportação, inimigos, atributos, tempo, melhorias e isolamento do ranking")
 call_deferred("quit")
